### ISSUE TITLE
Use tidy eval for node and edge parameters in layouts

### ISSUE THREAD

**Issue by thomasp85** [schochastics/graphlayouts#18]
The convention in the next ggraph release is that any argument to layouts that refer to some property of nodes or edges are using tidy evaluation. This has huge benefits as it means you don't need to modify the graph structure to change layout parameters.

Would it be possible to change the `layout_tbl_graph_*()` functions to follow this approach, or alternatively remove them and let me implement them directly in ggraph (then you wouldn't need to worry about the interface)

**Comment by schochastics** [comment]
Ok I guess you are the expert here: What of the two makes more sense:
1) I keep the layout_tbl_graph_*() in graphlayouts and make the changes
2) you implement layout_tbl_graph_*()  in ggraph?  

I assume that 1) might be better, since you would not have to update anything in ggraph if a new layout algorithm is added to graphlayouts. 

but if you think 2) is the way to go, then I am more than happy to shift the "burden" over to you :).
Most of the algorithms I wanted to have in the package are there now anyway and I do not plan any bigger changes in the near future. Also, I could always sync updates with bigger updates of ggraph.

**Comment by thomasp85** [comment]
I think if we end up
Making graphlayouts a hard dependency of ggraph it would make sense to have ggraph-specific code in ggraph and let graphlayouts be a general engine package with as low a dependency footprint as possible. After the next ggraph release I plan on doing more incremental release as with ggforce so new layouts can quickly be integrated

**Comment by schochastics** [comment]
Ok then I will remove the layout_tbl_graph_*() again and leave the rest to you
