### ISSUE TITLE
Allow specifying start position of nodes

### ISSUE THREAD

**Issue by thomasp85** [schochastics/graphlayouts#20]
While not being fully clear on the underlying algorithms, most layout algorithms sample some start position of the nodes and then iterate on that. In igraph it is possible to provide the start position and it only sample if none is given. Will this be possible for the layouts herein as well?

**Comment by schochastics** [comment]
`layout_with_stress()` can be initialized with an mds layout (specified with mds=TRUE). But ultimately it does not matter for any of the algorithms in graphlayouts, because all algorithms are deterministic (up to rotations and maybe minimal shifts, but not as crazy as some of the igraph layouts). The results will always be independent of the chosen initial layout. 

I am actually thinking about hardcoding a set seed in most layout function to always return the exact same result to get rid of the rotation problem. I know that this is done in some other software for stress layouts.

**Comment by thomasp85** [comment]
I see... so if you had a dynamic network and calculated the layout at time t and time t+Δ you’d get two layouts that were pretty close to each other (assuming not a lot happened in Δ time?

**Comment by schochastics** [comment]
Yes...probably but the rotation of the layout may well be different. For dynamic networks, there are better options:
[This](https://kops.uni-konstanz.de/bitstream/handle/123456789/20924/Brandes_209246.pdf?sequence=2) is pretty good. Is actually on my list. maybe I give it a go over the weekend.
