### ISSUE TITLE
Color palette limitations

### ISSUE THREAD

**Issue by ndjackso** [schochastics/graphlayouts#67]
Issue related to [openjournals/joss-reviews#5238](https://github.com/openjournals/joss-reviews/issues/5238)

**Comment by schochastics** [comment]
>   I received a warning when changing color palettes in the Backbone layout example:
    “Warning: n too large, allowed maximum for palette Dark2 is 8 Returning the palette you asked for with that many colors”.
I also encountered this warning with Set2, Pastel2, and Accent palettes in RColorBrewer. This issue appears to stem from the palette choice and not the graphlayouts package. One of the package’s strengths is being able to visualize very large networks. A couple of thoughts to overcome the warning:
   Consider adding a recommended of a color palette that works for large networks as part of the warning
    Considering including a default color palette that works for large n to override limited palettes

Yeah Set1 is afaik the only discrete color palette from RColorBrewer that allows 9 colors. I am reluctant to change anything here though, because I do not think this is an issue that `graphlayouts` needs to solve. Color palettes are to some extend subjective, and I do not want to define a default here. let me know if you disagree strongly here and I can implement something. Otherwise just close the issue

**Comment by ndjackso** [comment]
I was on the fence about including the warning as an issue recognizing that it might be beyond scope of the package. Color palettes are subjective. However, the package integrates well with other visualization packages where users can find something that works for them. Glad to have had this discussion, and I'm okay with closing the issue.
